set(CPACK_GENERATOR "DEB")
set(CPACK_CMAKE_GENERATOR "Unix Makefiles")

set(CPACK_PACKAGE_NAME "picaso-xcoreengine-mingw-w64")
set(CPACK_PACKAGE_VENDOR "PICASO 3D")
set(CPACK_PACKAGE_DESCRIPTION "Picaso XCore Engine statically compiled for MinGW-w64 targeting Win64")
set(CPACK_PACKAGE_CONTACT "Andrey Isupov <info@picaso-3d.ru>")
set(CPACK_PACKAGING_INSTALL_PREFIX "/usr/x86_64-w64-mingw32")
set(CPACK_PACKAGE_VERSION "01.04.50")
set(CPACK_DEBIAN_PACKAGE_RELEASE 1)
set(CPACK_PACKAGE_FILE_NAME "${CPACK_PACKAGE_NAME}_${CPACK_PACKAGE_VERSION}-${CPACK_DEBIAN_PACKAGE_RELEASE}")

set(CPACK_DEBIAN_PACKAGE_NAME "${CPACK_PACKAGE_NAME}")
set(CPACK_DEBIAN_PACKAGE_DESCRIPTION "${CPACK_PACKAGE_DESCRIPTION}")
set(CPACK_DEBIAN_PACKAGE_MAINTAINER "${CPACK_PACKAGE_CONTACT}")
set(CPACK_DEBIAN_PACKAGE_VERSION "${CPACK_PACKAGE_VERSION}")
set(CPACK_DEBIAN_FILE_NAME "${CPACK_PACKAGE_FILE_NAME}.deb")
set(CPACK_DEBIAN_PACKAGE_ARCHITECTURE "all")
set(CPACK_DEBIAN_PACKAGE_SECTION "devel")
set(CPACK_DEBIAN_PACKAGE_PRIORITY "optional")

set(_PicasoXCore_DEB_DEPENDS
  "cura-libprotobuf-dev (>= 3.9.2)"
  "cura-libprotobuf-mingw-w64-dev (>= 3.9.2)"
  "cura-libarcus-mingw-w64-dev (>= 4.5.0)"
)
string(REPLACE ";" ", " _PicasoXCore_DEB_DEPENDS "${_PicasoXCore_DEB_DEPENDS}")
set(CPACK_DEBIAN_PACKAGE_DEPENDS "${_PicasoXCore_DEB_DEPENDS}")
